// Generated by ChatGPT/Claude - reviewed by [Aaron González] - 15/04/2026

const express = require('express');
const router = express.Router();

// Handler para GET /weather/:city
router.get('/weather/:city', (req, res) => {
    try {
        const city = req.params.city;

        // 1. Validación de inputs básica
        if (!city || city.trim() === '') {
            return res.status(400).json({
                success: false,
                data: null,
                error: 'El parámetro ciudad es obligatorio.'
            });
        }

        // 1.1 Validación estricta (Edge case: una ciudad no debería tener números)
        if (/\d/.test(city)) {
            return res.status(400).json({
                success: false,
                data: null,
                error: 'El nombre de la ciudad no puede contener números.'
            });
        }

        // 2. Lógica simulada (Mock Data)
        const mockData = {
            city: city.trim(),
            temperature: 24,
            condition: 'Soleado',
            humidity: '45%'
        };

        // 3. Respuesta exitosa
        return res.status(200).json({
            success: true,
            data: mockData,
            error: null
        });

    } catch (error) {
        // 4. Manejo de errores con try/catch (sin exponer detalles del servidor)
        console.error('Error en GET /weather:', error);
        return res.status(500).json({
            success: false,
            data: null,
            error: 'Error interno del servidor.'
        });
    }
});

module.exports = router;